service: scraper

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    NEXMO_API_KEY: '0885eb53'
    NEXMO_API_SECRET: 'OY7SijGyjbHbgiER'

functions:
  getData:
    handler: handler.getData
