service: scraper

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getData:
    handler: handler.getData
resources:
  Resources:
    jobs:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: jobs
        AttributeDefinitions:
          - AttributeName: listingId
            AttributeType: S
        KeySchema:
          - AttributeName: listingId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: jobs
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: arn:aws:dynamodb:*:*:table/jobs
        Roles:
          - Ref: IamRoleLambdaExecution
